# Generated by Django 3.1.1 on 2020-09-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_platform', '0002_create_initial_interested_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
