# Generated by Django 3.1.1 on 2020-09-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_platform', '0005_customuser_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='areas',
        ),
    ]
