# Generated by Django 3.1.1 on 2020-09-16 23:33

from django.db import migrations, models
import food_platform.models


class Migration(migrations.Migration):

    dependencies = [
        ('food_platform', '0008_auto_20200916_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_Image',
            field=models.ImageField(default='img/default-image.png', upload_to=food_platform.models.get_image_path),
        ),
    ]
