# Generated by Django 3.1.1 on 2020-09-16 23:37

from django.db import migrations, models
import food_platform.models


class Migration(migrations.Migration):

    dependencies = [
        ('food_platform', '0009_auto_20200916_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_Image',
            field=models.ImageField(blank=True, upload_to=food_platform.models.get_image_path),
        ),
    ]
