# Generated by Django 3.1.1 on 2020-09-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_platform', '0011_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
